version: '2'

services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data

  odoo17:
    build:
      context: .
      dockerfile: Dockerfile.odoo-custom
    depends_on:
      - db
    ports:
      - "8069:8069"
    tty: true
    command: --
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
    volumes:
      - ./addons:/mnt/extra-addons
      - ./etc/:/etc/odoo
      # - ./entrypoint.sh:/entrypoint.sh # if you want to install additional Python packages, uncomment this line!
    restart: always


volumes:
  pgdata:
